version: '3.8'
services:
  kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENER_NAME_INSIDE: INSIDE
      KAFKA_LISTENER_NAME_OUTSIDE: OUTSIDE
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ZOOKEEPER_CONNECT_TIMEOUT_MS: 1500
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE  # This should match one of your defined listeners
    ports:
      - "9093:9093"
      - "9094:9094"
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:latest  # Update to a different version of Zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
